### ISSUE TITLE
Only calls imgSrcset()

### ISSUE THREAD

**Issue by jacobbf** [bnomei/kirby3-srcset#11]
Hi! 

Thanks so much for your work on this plugin - been using it since the release of Kirby 3 and it's been great. With the new update it doesn't seem to be calling the picture tag snippet, I've tried all the file methods and all of them seem to only make an img srcset tag - no picture tag or sources. 

I fiddled around a bit in the index.php, swapping out places you call the snippets and this seems to be the case - I got it to call the picture tag by snippet referenced on this line: 

`'plugin-srcset-img' => __DIR__ . '/snippets/srcset-img.php',` 

Hopefully you can figure out why.

**Comment by bnomei** [comment]
there where `.`instead of `,` at the file method definitions. thanks for reporting this bug.
