### ISSUE TITLE
kirby3-srcset breaks distantnative/retour-for-kirby

### ISSUE THREAD

**Issue by mourique** [bnomei/kirby3-srcset#26]
I'm not sure what the cause is, so i don't have a lot to go from. If bnomei/kirby3-srcset ist installed, either via composer or direct download, distantnative/retour-for-kirby will break. 
It disappears from the menu in the panel and the page for retour goes blank.

I confirmed this in a blank plainkit install. I am on kirby v3.3.6 with php v7.3.11. 

If someone could point to a place i could look and provide more information, i'd be glad to do so!

Can the issue be recreated, or is this something on my site?

**Comment by bnomei** [comment]
sorry to respond so late. does this issue still exist?

**Comment by mourique** [comment]
unfortunatly, yes, when kirby3-srcset is installed retour-for-kirby will not display. tried it on a blank plainkit install.

**Comment by bnomei** [comment]
to make this easier for me please zip and attach that test. thanks.

**Comment by mourique** [comment]
sure! 

[retour-test.zip](https://github.com/bnomei/kirby3-srcset/files/5074901/retour-test.zip)

**Comment by saltandbits** [comment]
Hey, seems like this issue is coming up again. Retour plugin stops working when you install srcset next to it.
Here is an example with the plainkit (kirby version 3.5): 
[retour-srcset.zip](https://github.com/bnomei/kirby3-srcset/files/5698126/retour-srcset.zip)
