### ISSUE TITLE
lazysrcset can not create srcset from null

### ISSUE THREAD

**Issue by gsperk** [bnomei/kirby3-srcset#28]
I've just updated some submodules in a Kirby3 web site.

I noticed that this change has broken my usage of kirby3-srcset: https://github.com/bnomei/kirby3-srcset/compare/v3.3.3...v3.3.4

I get:
<img alt="lazysrcset can not create srcset from null">

If I change back to v.3.3.3 the images load again.

I'm creating lazysrcset tags in a Kirby text field:
(lazysrcset: real-estate-banner.png imgclass: radius)

This works:
(image: real-estate-banner.png imgclass: radius)

Were there any other changes to make with v3.3.4 and up?

**Comment by bnomei** [comment]
that versions started using the `image()` helper... not sure exactly why anyone. i need to look that up.
that helper uses [this logic](https://github.com/getkirby/kirby/blob/29b36fffa6527804ac0fdea757c77878c3ccd1b8/config/helpers.php#L275) to get the current page as parent.

in what bigger context are you parsing the field as kirbytext? just this one page template or is a loop of pages?

**Comment by sigistardust** [comment]
i have the same problem. i had to go back to v3.3.2 and kirby v3.3.6 to get everything to work properly.

**Comment by gsperk** [comment]
> in what bigger context are you parsing the field as kirbytext? just this one page template or is a loop of pages?

My case is a Kirby page with subpages rendering as a single page.
Some of the subpages are inserted in a loop.

**Comment by bnomei** [comment]
https://github.com/bnomei/kirby3-srcset/releases/tag/v3.3.11
