### ISSUE TITLE
Srcset with comma instead of period

### ISSUE THREAD

**Issue by thisisdelphin** [bnomei/kirby3-srcset#34]
I'm using your plugin and everything is fine, but I'm using it for a french website where we use commas instead of periods for decimals. That breaks the css and I don't know what to do.

`<style>.lazysrcset-ratio[data-ratio="37,51"]{padding-bottom:37,51%;}</style>`

**Comment by bnomei** [comment]
sorry for the late fix. i am in parental leave right now.
