### ISSUE TITLE
Classes are not added when using the Kirby tag

### ISSUE THREAD

**Issue by obear** [bnomei/kirby3-srcset#7]
When I use the kirbytag in connection with a class `(srcset: 01.jpg class: w-1/2)`, the class is not added to the picture (or image) element.  

When I use the kirbytag in connection with a class and a link `(srcset: 01.jpg class: w-1/2 link: 01.jpg)`, the class is added to the enclosing a tag.

**Comment by bnomei** [comment]
thanks for reporting this issue i will fix it later today.

**Comment by bnomei** [comment]
i do not have the time to fully test it today. but you can use the prerelease zip if you want to until then.
https://github.com/bnomei/kirby3-srcset/releases/tag/v1.4.0-alpha

**Comment by bnomei** [comment]
i think i used the old k2 attributes. it should work pretty much link the k3 `(image: ...)` now. it is not as smart with the `link`attr as the `(image:...)` is but i do not have time to do that now.

https://getkirby.com/docs/reference/text/kirbytags/image

**Comment by obear** [comment]
Thanks. For me it works now! 👍
